### ISSUE TITLE
Infinite Loop (Reboot) Continuous ECG mode

### ISSUE THREAD

**Issue by Badr1600** [Protocentral/protocentral_heartypatch#13]
Error: 18:31:30.257 -> ESP_ERROR_CHECK failed: esp_err_t 0x110c at 0x400df5f5
18:31:30.257 -> file: "C:/msys32/home/100703599/esp/esp-idf/protocentral_heartypatch/firmware/heartypatch-stream-tcp/main/main.c" line 78
18:31:30.257 -> func: kalam_wifi_init
18:31:30.257 -> expression: esp_wifi_init(&cfg)

Complete Trace of Serial Monitor:

18:31:26.696 -> ⸮ets Jun  8 2016 00:22:57
18:31:28.562 -> 
18:31:28.562 -> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
18:31:28.562 -> configsip: 0, SPIWP:0x00
18:31:28.562 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
18:31:28.562 -> mode:DIO, clock div:3
18:31:28.562 -> load:0x3fff0008,len:8
18:31:28.562 -> load:0x3fff0010,len:4396
18:31:28.562 -> ho 0 tail 12 room 4
18:31:28.562 -> load:0x40078000,len:11080
18:31:28.562 -> ho 0 tail 12 room 4
18:31:28.562 -> load:0x40080000,len:252
18:31:28.562 -> entry 0x40080034
18:31:28.562 -> [0;32mI (33) boot: ESP-IDF v2.1-dirty 2nd stage bootloader[0m
18:31:28.562 -> [0;32mI (33) boot: compile time 18:24:24[0m
18:31:28.562 -> [0;32mI (60) boot: Enabling RNG early entropy source...[0m
18:31:28.562 -> [0;32mI (60) boot: SPI Speed      : 26.7MHz[0m
18:31:28.562 -> [0;32mI (61) boot: SPI Mode       : DIO[0m
18:31:28.562 -> [0;32mI (73) boot: SPI Flash Size : 4MB[0m
18:31:28.562 -> [0;32mI (85) boot: Partition Table:[0m
18:31:28.562 -> [0;32mI (96) boot: ## Label            Usage          Type ST Offset   Length[0m
18:31:28.562 -> [0;32mI (119) boot:  0 nvs              WiFi data        01 02 00009000 00006000[0m
18:31:28.562 -> [0;32mI (142) boot:  1 phy_init         RF data          01 01 0000f000 00001000[0m
18:31:28.562 -> [0;32mI (165) boot:  2 factory          factory app      00 00 00010000 00100000[0m
18:31:28.562 -> [0;32mI (189) boot: End of partition table[0m
18:31:28.562 -> [0;32mI (202) boot: Disabling RNG early entropy source...[0m
18:31:28.562 -> [0;32mI (219) boot: Loading app partition at offset 00010000[0m
18:31:29.004 -> [0;32mI (1142) boot: segment 0: paddr=0x00010018 vaddr=0x00000000 size=0x0ffe8 ( 65512) [0m
18:31:29.004 -> [0;32mI (1143) boot: segment 1: paddr=0x00020008 vaddr=0x3f400010 size=0x0dd20 ( 56608) map[0m
18:31:29.004 -> [0;32mI (1159) boot: segment 2: paddr=0x0002dd30 vaddr=0x3ffb0000 size=0x02b1c ( 11036) load[0m
18:31:29.004 -> [0;32mI (1192) boot: segment 3: paddr=0x00030854 vaddr=0x40080000 size=0x00400 (  1024) load[0m
18:31:29.004 -> [0;32mI (1213) boot: segment 4: paddr=0x00030c5c vaddr=0x40080400 size=0x13a2c ( 80428) load[0m
18:31:29.004 -> [0;32mI (1292) boot: segment 5: paddr=0x00044690 vaddr=0x400c0000 size=0x00000 (     0) load[0m
18:31:29.004 -> [0;32mI (1293) boot: segment 6: paddr=0x00044698 vaddr=0x00000000 size=0x0b970 ( 47472) [0m
18:31:29.004 -> [0;32mI (1309) boot: segment 7: paddr=0x00050010 vaddr=0x400d0018 size=0x4bc9c (310428) map[0m
18:31:29.004 -> [0;32mI (1335) cpu_start: Pro cpu up.[0m
18:31:29.004 -> [0;32mI (1347) cpu_start: Starting app cpu, entry point is 0x40080ed4[0m
18:31:29.004 -> [0;32mI (0) cpu_start: App cpu up.[0m
18:31:29.004 -> [0;32mI (1380) heap_alloc_caps: Initializing. RAM available for dynamic allocation:[0m
18:31:29.004 -> [0;32mI (1402) heap_alloc_caps: At 3FFAE2A0 len 00001D60 (7 KiB): DRAM[0m
18:31:29.004 -> [0;32mI (1423) heap_alloc_caps: At 3FFB8938 len 000276C8 (157 KiB): DRAM[0m
18:31:29.004 -> [0;32mI (1444) heap_alloc_caps: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM[0m
18:31:29.004 -> [0;32mI (1465) heap_alloc_caps: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
18:31:29.004 -> [0;32mI (1487) heap_alloc_caps: At 40093E2C len 0000C1D4 (48 KiB): IRAM[0m
18:31:29.004 -> [0;32mI (1508) cpu_start: Pro cpu start user code[0m
18:31:29.004 -> [0;32mI (1572) cpu_start: Starting scheduler on PRO CPU.[0m
18:31:29.004 -> [0;32mI (212) cpu_start: Starting scheduler on APP CPU.[0m
18:31:29.614 -> [0;32mI (837) heartypatch:: max30003_initchip setting SPS to 128[0m
18:31:29.614 -> [0;32mI (837) heartypatch:: max30003_initchip DHPF Disabled[0m
18:31:30.086 -> E (1341) wifi: misc_nvs_load 208 ret=4364
18:31:30.257 -> E (1341) wifi: wifi_init 1355 ret=4364
18:31:30.257 -> ESP_ERROR_CHECK failed: esp_err_t 0x110c at 0x400df5f5
18:31:30.257 -> file: "C:/msys32/home/100703599/esp/esp-idf/protocentral_heartypatch/firmware/heartypatch-stream-tcp/main/main.c" line 78
18:31:30.257 -> func: kalam_wifi_init
18:31:30.257 -> expression: esp_wifi_init(&cfg)
18:31:30.257 -> 
18:31:30.257 -> Backtrace: 0x40087550:0x3ffb9790 0x400878cd:0x3ffb97b0 0x400df5f5:0x3ffb97d0 0x400df6fd:0x3ffb9890 0x400d0b42:0x3ffb98b0
18:31:30.257 -> 
18:31:30.257 -> Rebooting...

**Comment by Badr1600** [comment]
![error](https://user-images.githubusercontent.com/9883712/60847415-9c4b3000-a1b0-11e9-8efd-7bd724ae69af.PNG)

C:/msys32/home/100703599/esp/esp-idf/protocentral_heartypatch/firmware/heartypatch-stream-tcp/main/main.c: In function 'kalam_wifi_init':
C:/msys32/home/100703599/esp/esp-idf/protocentral_heartypatch/firmware/heartypatch-stream-tcp/main/main.c:92:17: warning: unused variable 'err' [-Wunused-variable]
       esp_err_t err = mdns_init(TCPIP_ADAPTER_IF_STA, &mdns);


This message also is printed when using "make" to generate the .bin files for the Continuous ECG mode

**Comment by styck** [comment]
I modified the code as shown below.  Keep in mind that I also used a newer tool chain than the one recommended.

//#ifdef CONFIG_MDNS_ENABLE
//      esp_err_t err = mdns_init(TCPIP_ADAPTER_IF_STA, &mdns);
//      ESP_ERROR_CHECK( mdns_set_hostname(mdns, KALAM32_MDNS_NAME) );
//      ESP_ERROR_CHECK( mdns_set_instance(mdns, KALAM32_MDNS_NAME) );
//#endif
#ifdef CONFIG_MDNS_ENABLE
      ESP_ERROR_CHECK( mdns_init() );
      ESP_ERROR_CHECK(mdns_hostname_set(KALAM32_MDNS_NAME));
      ESP_ERROR_CHECK(mdns_instance_name_set(KALAM32_MDNS_NAME));
#endif

**Comment by Badr1600** [comment]
@styck still having the same issue. Can you share the .bin files that you built for the continuous ecg firmware to burn it directly to the module. just to verify the idea

**Comment by styck** [comment]
This is a zip file with the bin and map file for my build.
[build.zip](https://github.com/Protocentral/protocentral_heartypatch/files/3379613/build.zip)

**Comment by Badr1600** [comment]
I think there should be three .bin files heartypatch_tcp.bin, partitions_singleapp.bin and bootloader.bin right ??

**Comment by styck** [comment]
Ok, added the bootloader.bin.

[HeartyPatchTCPBinary.zip](https://github.com/Protocentral/protocentral_heartypatch/files/3379706/HeartyPatchTCPBinary.zip)

**Comment by Badr1600** [comment]
Great! the firmware is flashed successfully but what is the WiFi ssid and password that was used in the configuration file.

**Comment by awhitchurch** [comment]
Thanks @styck @Badr1600 for solving this issue.  We will upload a new release with the bin files for the continuous ECG mode.

**Comment by Badr1600** [comment]
@protocentralashwin Thank you as I think there are some comparability issues with the current esp tool chain and esp-idf while building the firmware. Would be great if you update the instructions on the official website for setting up the firmware to the continuous ECG mode

**Comment by Badr1600** [comment]
> I modified the code as shown below. Keep in mind that I also used a newer tool chain than the one recommended.
> 
> //#ifdef CONFIG_MDNS_ENABLE
> // esp_err_t err = mdns_init(TCPIP_ADAPTER_IF_STA, &mdns);
> // ESP_ERROR_CHECK( mdns_set_hostname(mdns, KALAM32_MDNS_NAME) );
> // ESP_ERROR_CHECK( mdns_set_instance(mdns, KALAM32_MDNS_NAME) );
> //#endif
> #ifdef CONFIG_MDNS_ENABLE
> ESP_ERROR_CHECK( mdns_init() );
> ESP_ERROR_CHECK(mdns_hostname_set(KALAM32_MDNS_NAME));
> ESP_ERROR_CHECK(mdns_instance_name_set(KALAM32_MDNS_NAME));
> #endif

What is the version of tool chain have used ?

**Comment by styck** [comment]
Today I just updated to the latest of everything (esp32 and msys32) following the instructions for Windows here: https://docs.espressif.com/projects/esp-idf/en/stable/get-started/index.html

There are only a few minor changes that had to be made to the heartypatch code, which I forked and will check in my changes, they just built but I have tested on the device.

I would like to add support for Wifi so I don't have to hard code the SSID and password, seems possible looking at: https://github.com/nkolban/esp32-snippets/tree/master/networking/bootwifi
![HeartyPatchWorking](https://user-images.githubusercontent.com/1245448/61178500-a1d6ba80-a5a2-11e9-9f07-c51714f3f24f.png)

**Comment by Badr1600** [comment]
> Today I just updated to the latest of everything (esp32 and msys32) following the instructions for Windows here: https://docs.espressif.com/projects/esp-idf/en/stable/get-started/index.html
> 
> There are only a few minor changes that had to be made to the heartypatch code, which I forked and will check in my changes, they just built but I have tested on the device.
> 
> I would like to add support for Wifi so I don't have to hard code the SSID and password, seems possible looking at: https://github.com/nkolban/esp32-snippets/tree/master/networking/bootwifi
> ![HeartyPatchWorking](https://user-images.githubusercontent.com/1245448/61178500-a1d6ba80-a5a2-11e9-9f07-c51714f3f24f.png)

Working!!  
Fix:
comment this line in file main.c since this attribute is never used and it always raises an error while building the firmware.
//mdns_server_t * mdns = NULL;

**Comment by joicetm** [comment]
We are glad that you are able to fix it @Badr1600 @styck . We have updated the release with binaries with mdns and hard coded wifi ssid/password.

There is an example for setting the wifi ssid and password in esp-idf using ble, soft ap and uart console.

```
/esp-idf/examples/provisioning
```
