### ISSUE TITLE
Hardware: Beware of original USB cable

### ISSUE THREAD

**Issue by tbaumann** [Protocentral/protocentral_heartypatch#15]
I had persistent issues flashing my new HeartyPatch.

Turns out, the USB cable delivered with the device is junk. It works fine with a good one.

To users: Toss it away.

To manufacturer: Leave it out. Everybody has a box full of USB cables. There is no need to bring more junk into the world.

**Comment by awhitchurch** [comment]
@tbaumann Thank you for the suggestion. We haven't seen this issue yet, but will watch out in our future batch of cables
