### ISSUE TITLE
setting it up in ubuntu

### ISSUE THREAD

**Issue by sanster9292** [Protocentral/protocentral_heartypatch#4]
Hey guys, 
Sorry to put it here, but i just got my heartypatch and I was wondering how i would set it up for use to play around with. I am trying to use the data for some R-R interval realted project I am working on. I was trying to find the link to download the GUI software but I couldn't find any links or tutorials for that. 
Any help would be greatly appreciated

**Comment by joicetm** [comment]
Hi,

I am closing this issue as it was addressed through mail, you can reopen or create new issue in case of any query



You can check our documentation site for [getting started](http://heartypatch.protocentral.com/)

To record the data you may use the log button in the heartypacth application. which will save the data to a .csv file in downloads section.

[android app](https://play.google.com/store/apps/details?id=com.protocentral.heartypatch&hl=en)

You can also use HeartyPatch GUI to recoed the data while in [TCP mode](https://github.com/Protocentral/protocentral_heartypatch/releases/tag/v1.0)
